---
seed: 42


# Domain settings ......................................................................................................
space:
  dimension: 2

  # The domain boundary
  boundary:
    x: [-1, 1]
    y: [-1, 1]

  # The grid size. Should be at least 3.
  grid_size:
    x: 10
    y: 30

# PDE parameters .......................................................................................................
PDE:
  type: !param
    default: Poisson
    is_any_of: [Poisson, Burger, Helmholtz, Weak1D, PorousMedium]
  function: !param
    default: Tanh2D
    dtype: str
    is_any_of: [Tanh, Tanh2D, SinSin2D, Burger1+1D, DoubleGauss1D, CubedRoot, PorousMedium]
  PorousMedium:
    m: 2
  Helmholtz:
    k: -2.5
  Burger:
    nu: !is-positive-or-zero 0

# The variational form to use; can be 0, 1, or 2
variational_form: 2

# Test function settings ...............................................................................................
test_functions:
  N_test_functions:
    x: 10
    y: 10

  # Type: can be Legendre, Chebyshev, or Sine
  type: Legendre

  # Whether to weight the test functions
  weight_function: !param
    default: exponential
    is_any_of: [uniform, exponential]

# Neural net architecture ..............................................................................................
NeuralNet:
  num_layers: !is-positive-int 4
  nodes_per_layer: !is-positive-int 20
  activation_funcs: relu
  optimizer: !param
    default: Adam
    is_any_of: [Adagrad, Adam, AdamW, SparseAdam, Adamax, ASGD, LBFGS, NAdam, RAdam, RMSprop, Rprop, SGD]
  learning_rate: 0.001


# Training settings ....................................................................................................
Training:
  device: cpu
  batch_size: 1
  learning_rate: 0.001
  boundary_loss_weight: 1
  variational_loss_weight: 1

# Settings for the prediction grid (optional) ..........................................................................
predictions_grid:
  grid_size:
    x: 100
    y: 100
