---
# Domain settings ......................................................................................................
load_from_dir: ~

space:
  x:
    extent: [-1, 1]
    size: 20

# PDE parameters .......................................................................................................
PDE:
  type: Poisson
  function: Tanh
  PorousMedium:
    m: 2
  Helmholtz:
    k: -2.5
  Burger:
    nu: 0

# The variational form to use; can be 0, 1, or 2
variational_form: 0

# Test function settings ...............................................................................................
test_functions:
  num_functions:
    n_x:
      size: 3
  type: !param
    default: Legendre
    dtype: str
    is_any_of: [Legendre, Chebyshev, Sine]

  # The type of weighting to use
  weight_function: !param
    default: exponential
    is_any_of: [uniform, exponential]


# Neural net architecture ..............................................................................................
NeuralNet:
  num_layers: 4
  nodes_per_layer: 20
  activation_funcs: sin
  optimizer: !param
    default: Adam
    is_any_of: [Adagrad, Adam, AdamW, SparseAdam, Adamax, ASGD, LBFGS, NAdam, RAdam, RMSprop, Rprop, SGD]

# Training settings ....................................................................................................
Training:
  device: cpu
  batch_size: 1
  learning_rate: 0.001
  boundary_loss_weight: 1
  variational_loss_weight: 1
