---
seed: 42


# Domain settings ......................................................................................................
space:
  dimension: 2

  # The domain boundary
  boundary:
    x: [-1, 1]
    y: [-1, 1]

  # The grid size. Should be at least 3.
  grid_size:
    x: 10
    y: 30

# PDE parameters .......................................................................................................
PDE:
  type: Poisson
  PorousMedium:
    m: 2
  Helmholtz:
    k: -2.5
  Burger:
    nu: 0

# The variational form to use; can be 0, 1, or 2
variational_form: 2

# Test function settings ...............................................................................................
Test functions:
  N_test_functions:
    x: 10
    y: 10

  # Type: can be Legendre, Chebyshev, or Sine
  type: Legendre

  # Whether to weight the test functions
  weighting: True

# Neural net architecture ..............................................................................................
architecture:
  layers: 4
  nodes_per_layer: 20

# Training settings ....................................................................................................
N_iterations: 1000
learning_rate: 0.001
boundary_loss_weight: 1
variational_loss_weight: 1

# Plot settings ........................................................................................................
plots:
  plot_resolution:
    x: 120
    y: 120
  plot_animation: False
  plot_info_box: False
  write_loss_data: True

  # these are passed to matplotlib.rcParams
  rcParams:
    text.usetex: False
    mathtext.fontset: 'stix'
    font.family: 'serif'
    font.size: 12
    figure.figsize: [8, 8]
    lines.linewidth: 6
    figure.autolayout: True
