---
seed: 42


# Domain settings ......................................................................................................
space:
  dimension: 2

  # The domain boundary
  boundary:
    x: [-3, 3]
    y: [0.1, 2]

  # The grid size. Should be at least 3.
  grid_size:
    x: 20
    y: 20

# PDE parameters .......................................................................................................
PDE:
  type: PorousMedium
  PorousMedium:
    m: 2
  Helmholtz:
    k: -2.5
  Burger:
    nu: 0

# The variational form to use; can be 0, 1, or 2
variational_form: 1

# Test function settings ...............................................................................................
Test functions:
  # Can be Legendre, Chebyshev, or Sine
  type: Legendre
  N_test_functions:
    x: 10
    y: 10
  # Whether to weight the test functions
  weighting: False

# Neural net architecture ..............................................................................................
architecture:
  layers: 4
  nodes_per_layer: 20

# Training settings ....................................................................................................
N_iterations: 1000
learning_rate: 0.001
boundary_loss_weight: 1
variational_loss_weight: 1

# Plot settings ........................................................................................................
plots:
  plot_resolution:
    x: 120
    y: 120
  plot_animation: False
  plot_info_box: False
  # these are passed to matplotlib.rcParams
  rcParams:
    text.usetex: True
    mathtext.fontset: 'stix'
    font.family: 'serif'
    font.size: 24
    figure.figsize: [14, 12]
    lines.linewidth: 6
    figure.autolayout: True
