---
seed: 42

# PDE settings .................................................................

# The space, equation, and external forcing
space:
  dimension: 1
  # The domain boundary, given as [[x_0, x_1], [y_0, y_1]]
  boundary: [-1, 1]
  # The grid size. For 2d, this should be an array. For 1d, this should be a scalar.
  grid_size: 2
PDE:
  type: Poisson
  Helmholtz:
    k: -0.4
  Burger:
    nu: 0.3

# Test function settings .......................................................
# The variational form to use; can be 1, 2, or 3
variational_form: 1

# The number of test functions to use. Test functions are Jacobi polynomials.
N_test_functions: 3

# number of quadrature points
N_quad: 60

# Neural net architecture ......................................................
architecture:
  layers: 4
  nodes_per_layer: 20

# Training settings ............................................................
N_iterations: 1000
learning_rate: 0.001
loss_weight: 1

# Plot settings ................................................................
plots:
  plot_points: 100
  color: blue
  rcParams:
    text.usetex: True
    mathtext.fontset: 'stix'
    font.family: 'serif'
    font.size: 20
    figure.figsize: [10, 8]
    lines.linewidth: 3
    figure.autolayout: False
