---
seed: 42

# PDE settings .................................................................

# The space, equation, and external forcing
space:
  dimension: 2
  # The domain boundary, given as [[x_0, x_1], [y_0, y_1]]
  boundary: [[-1, 1], [-1, 1]]
  # The grid size. For 2d, this should be an array. For 1d, this should be a scalar.
  grid_size: [5, 4]
PDE:
  type: Burger
  Helmholtz:
    k: -0.4
  Burger:
    nu: 0.3

# Test function settings .......................................................
# The variational form to use; can be 1, 2, or 3
variational_form: 3

# The number of test functions to use. Test functions are Jacobi polynomials.
N_test_functions: 3

# number of quadrature points
N_quad: [4, 4]

## number of random points on which to evaluate f to use as training points
#N_f: 500

# Neural net architecture ......................................................
architecture:
  layers: 4
  nodes_per_layer: 60

# Training settings ............................................................
N_iterations: 10
learning_rate: 0.1
loss_weight: 1
batch_size: 10

# Plot settings ................................................................
plots:
  color: blue
rcParams:
  text.usetex: True
  mathtext.fontset: 'stix'
  font.family: 'serif'
  font.size: 20
  figure.figsize: [10, 8]
  lines.linewidth: 3
  figure.autolayout: True
