---
paths:
  model_note: dummy
perform_sweep: True
parameter_space:
  num_epochs: 5000
  write_every: 20
  write_predictions_every: 20
  seed: !sweep
    default: 0
    range: [5]
  VPINN:
    load_data:
      data_dir: ~
    space:
      x:
        extent: [-1, 1 ]
        size: 60
    PDE:
      function: dummy
      type: dummy
    test_functions:
      type: Legendre
      num_functions:
        n_x:
          size: !sweep
            default: 10
            values: [5, 10, 20, 40]
            name: num_test_functions
      weight_function: uniform
    variational_form: 0
    NeuralNet:
      num_layers: 10
      nodes_per_layer:
        default: !sweep
          default: 10
          values: [10, 50, 100]
          name: nodes_per_layer
      activation_funcs:
        default: !sweep
          default: tanh
          values: [sine, tanh]
          name: activation_func
    Training:
      device: cpu
      learning_rate: 0.001
      variational_loss_weight: 1
