---
paths:
  model_note: Poisson1D
parameter_space:
  num_epochs: 5000
  VPINN:
    space:
      x:
        extent: [-1, 1 ]
        size: 60
    PDE:
      function: Tanh
      type: Poisson
    test_functions:
      type: Legendre
      num_functions:
        n_x:
          size: 80
      weight_function: uniform
    variational_form: 0
    NeuralNet:
      num_layers: 4
      nodes_per_layer: 20
      activation_funcs:
        0: tanh
        1: tanh
        2: tanh
        3: tanh
        4: linear
    Training:
      device: mps
      learning_rate: 0.001
      variational_loss_weight: 20
    predictions_grid:
      x:
        size: 60
