---
paths:
  model_note: Poisson1D
parameter_space:
  num_epochs: 5000
  VPINN:
    load_data:
      data_dir: ~
    space:
      x:
        extent: [-1, 1 ]
        size: 60
    PDE:
      function: Tanh
      type: Poisson
    test_functions:
      type: Legendre
      num_functions:
        n_x:
          size: 80
      weight_function: uniform
    variational_form: 0
    NeuralNet:
      num_layers: 4
      nodes_per_layer:
        default: 20
      activation_funcs:
        default: tanh
        layer_specific:
          -1: linear
    Training:
      device: cpu
      learning_rate: 0.001
      variational_loss_weight: 20
    predictions_grid:
      x:
        size: 60
