---
seed: 42


# Domain settings ......................................................................................................
space:
  dimension: 2

  # The domain boundary
  boundary:
    x: [-2, 2]
    y: [0, 2]

  # The grid size. Should be at least 3.
  grid_size:
    x: 20
    y: 20

# PDE parameters .......................................................................................................
PDE:
  type: Burger
  PorousMedium:
    m: 2
  Helmholtz:
    k: 5
  Burger:
    nu: 0

# The variational form to use; can be 0, 1, or 2
variational_form: 1

# Test function settings ...............................................................................................
Test functions:
  type: Chebyshev
  N_test_functions:
    x: 10
    y: 10

# Neural net architecture ..............................................................................................
architecture:
  layers: 4
  nodes_per_layer: 20

# Training settings ....................................................................................................
N_iterations: 3000
learning_rate: 0.001
boundary_loss_weight: 2
variational_loss_weight: 1

# Plot settings ........................................................................................................
plots:
  plot_resolution:
    x: 100
    y: 120
  plot_animation: False
  # these are passed to matplotlib.rcParams
  rcParams:
    text.usetex: True
    mathtext.fontset: 'stix'
    font.family: 'serif'
    font.size: 24
    figure.figsize: [16, 12]
    lines.linewidth: 3
    figure.autolayout: True
