---
seed: 42

# PDE settings .................................................................

# The space, equation, and external forcing
space:
  dimension: 2

  # The domain boundary
  boundary:
    x: [-1, 1]
    y: [-1, 1]

  # The grid size. Should be at least 3.
  grid_size:
    x: 40
    y: 40

PDE:
  type: Poisson
  Helmholtz:
    k: -0.4
  Burger:
    nu: 0.3

# Test function settings .......................................................
# The variational form to use; can be 0, 1, or 2
variational_form: 1

# The number of test functions to use. Test functions are Jacobi polynomials.
N_test_functions:
  x: 30
  y: 30

# Neural net architecture ......................................................
architecture:
  layers: 1
  nodes_per_layer: 10

# Training settings ............................................................
N_iterations: 10000
learning_rate: 0.001
loss_weight: 1

# Plot settings ................................................................
plots:
  plot_resolution:
    x: 100
    y: 100
  color: blue
  # these are passed to matplotlib.rcParams
  rcParams:
    text.usetex: True
    mathtext.fontset: 'stix'
    font.family: 'serif'
    font.size: 20
    figure.figsize: [16, 9]
    lines.linewidth: 3
    figure.autolayout: True
