---
seed: 42

# PDE settings .................................................................

# The space, equation, and external forcing
space:
  dimension: 2

  # The domain boundary
  boundary:
    x: [-1, 1]
    y: [-1, 1]

  # The grid size. Should be at least 3.
  grid_size:
    x: 20
    y: 20

PDE:
  type: Poisson
  Helmholtz:
    k: -0.4
  Burger:
    nu: 0.3

# Test function settings .......................................................
# The variational form to use; can be 1, 2, or 3
variational_form: 1

# The number of test functions to use. Test functions are Jacobi polynomials.
N_test_functions:
  x: 10
  y: 10

# Neural net architecture ......................................................
architecture:
  layers: 4
  nodes_per_layer: 20

# Training settings ............................................................
N_iterations: 1000
learning_rate: 0.001
loss_weight: 10

# Plot settings ................................................................
plots:
  plot_resolution:
    x: 100
    y: 100
  color: blue
  # these are passed to matplotlib.rcParams
  rcParams:
    text.usetex: True
    mathtext.fontset: 'stix'
    font.family: 'serif'
    font.size: 20
    figure.figsize: [16, 9]
    lines.linewidth: 3
    figure.autolayout: True
